version: '3'
services:
  sql_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./database/sql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: T0XGfOR9dCkk366sCFOq
      MYSQL_DATABASE: 'fullproject'
      MYSQL_USER: 'app_client'
      MYSQL_PASSWORD: 'wJkEq3ejztAGp4DY'
    ports:
      - 3306:3306
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - sql_db
    ports:
      - 8100:80
    volumes:
      - ./src/:/var/www/html
    stdin_open: true
    tty: true
